openapi: '3.0.3'
info:
  title: katalog API
  version: '1.0'
  description: Katalog API
servers:
  - url: https://virtserver.swaggerhub.com/predic/katalog/1
paths:
  /artikel/:
    get:
      tags:
        - Shop
      summary: Gebe mir alle Artikel zurück
      description: Liefert alle Artikel zurück
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artikel'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artikel'
      tags:
        - Shop
      summary: Hiermit wird ein Artikel erstellt.
      description: | 
        # Ein Artikel wird erstellt.
        
        ## Dieser Endpunkt ist dazu da, um Artikel zu erstellen. Ein Artikel besteht aus:
        
        - Name
        - Preis
        
        Inline-style: 
        ![alt text](https://s3.eu-west-1.amazonaws.com/redsys-prod/articles/43c734f0791ad5a9f6fe6131/images/eschhold_softwarearchitektur2_2.tif_fmt1.jpg "Logo Title Text 1")
        
        | Tables        | Are           | Cool  |
        | ------------- |:-------------:| -----:|
        | col 3 is      | right-aligned | $1600 |
        | col 2 is      | centered      |   $12 |
        | zebra stripes | are neat      |    $1 |

        
        
      responses:
        '201':
          description: Created
          headers:
            Location:
              description: URI des neuen Artikels
              schema:
                type: string
                maxLength: 200
                format: uri
                example: https://api.myCompany.com/shop/v2/artikel/<123>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artikel'
  /artikel/{aid}:
    parameters:
      - in: path
        name: aid
        schema:
          type: string
        required: true
    get:
      tags:
        - Shop
      summary: Gebe einen Artikel zurück
      description: Ein Artikel wird zurück gegeben
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artikel'
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artikel'
      tags:
        - Shop
      summary: Ändere einen Artikel
      description: Ein Artikel wird geändert
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artikel'
        '4XX':
          description: Client Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '5XX':
          description: Server Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      tags:
        - Shop
      summary: Lösche einen Artikel
      description: Ein Artikel wird gelöscht
      responses:
        '200':
          description: ok
          
    patch:
      tags:
        - Shop
      summary: Aktualisiere entweder den Namen oder den Preis eines Artikels
      description: | 
        Ermöglicht die teilweise Aktualisierung eines Artikels. 
        Nur die Felder, die aktualisiert werden sollen, müssen im Request-Body enthalten sein.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArtikelPatch'
      responses:
        '200':
          description: Artikel erfolgreich aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artikel'
        '4XX':
          description: Client Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    
components:
  schemas:
    Artikel:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
          example: Grapefruit
          description: Dies ist der Name des Artikels
        preis:
          type: number
          minimum: 0 
          example: 0.99
          description: Dies ist der Preis des Artikels
      required:
        - name
        - preis
    ErrorMessage:
      type: object
      properties:
        developer-message:
          type: string
          maxLength: 2000
          example: Beschreibung des Client Fehlers in verständlicher Form.
          description: Beschreibung des Fehlers
        timestamp:
          type: string
          format: date-time
          maxLength: 200
        user-message:
          type: string
          maxLength: 2000
          example: UserMsg
          description: userMsg
    ArtikelPatch:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
          example: Neue Grapefruit
        preis:
          type: number
          minimum: 0 
          example: 1.49
      additionalProperties: false
          
          